resources:

  # ======================================================
  # Lab network (top-level resource)
  # ======================================================
  lab_network:
    type_name: lab_network
    id: 1
    name: "IaC"
    location: "US East"
    control_modules: ["clio"]

  # ======================================================
  # CONTROL MODULE 1
  # ======================================================
  clio:
    type_name: control_module
    id: 2
    endpoints: 
      - inventory_manager
    equipment:
      - valve
      - valve_end
      - valve_2
      - viscometer
      - palmsens4
      - balance
      - relay_24V
      - relay2V
      - pump_1
      - thermometer
      - pump_2

  # Endpoints for Clio 1
  inventory_manager:
    type_name: inventory_manager
    id: 3

  # Equipment for Clio 1
  valve:
    type_name: valve
    id: 4
    connection_type: serial
    identifier: 4
    baud_rate: 9600

  valve_end:
    type_name: valve
    id: 5
    connection_type: serial
    identifier: 5
    baud_rate: 9600

  valve_2:
    type_name: valve
    id: 6
    connection_type: serial
    identifier: 6
    baud_rate: 9600

  viscometer:
    type_name: viscometer
    id: 7
    connection_type: serial
    identifier: 7
    baud_rate: 9600

  palmsens4:
    type_name: potentiostat
    id: 8
    connection_type: serial
    identifier: 8
    baud_rate: 9600

  balance:
    type_name: balance
    id: 9
    connection_type: serial
    identifier: 9
    baud_rate: 9600

  relay_24V:
    type_name: relay
    id: 10
    connection_type: hid
    identifier: XFw/XEhJRCNWSURfMTZDMCZQSURfMDVERiM4JjIwZDg3NDJmJjAmMDAwMCN7NGQxZTU1YjItZjE2Zi0xMWNmLTg4Y2ItMDAxMTExMDAwMDMwfQ==

  relay2V:
    type_name: relay
    id: 11
    connection_type: hid
    identifier: XFw/XEhJRCNWSURfMTZDMCZQSURfMDVERiM4JmJlNDA3NDAmMCYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9

  pump_1:
    type_name: pump
    id: 12
    connection_type: serial
    identifier: 12
    baud_rate: 9600

  thermometer:
    type_name: thermometer
    id: 13
    connection_type: hid
    identifier: XFw/XEhJRCNWSURfNDY0RCZQSURfMDQwMiZNSV8wMSM5JmIyZDVmNjcmMCYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9

  pump_2:
    type_name: pump
    id: 14
    connection_type: serial
    identifier: 14
    baud_rate: 9600
