resources:

  # ======================================================
  # Lab network (top-level resource)
  # ======================================================
  lab_network:
    type_name: lab_network
    id: 1
    name: "IaC"
    location: "US East"
    control_modules: ["clio_1"]

  # ======================================================
  # CONTROL MODULE 1
  # ======================================================
  clio_1:
    type_name: control_module
    module_type: clio
    id: 2
    endpoints: 
      - inventory_manager
    equipment:
      - palmsens4
      - balance
      - pump_1
      - pump_2
      - valve
      - relay_1
      - relay_2

  palmsens4:
    type_name: potentiostat
    id: 8
    connection_type: serial
    identifier: 8
    baud_rate: 9600

  pump_1:
    type_name: pump
    id: 12
    connection_type: serial
    identifier: 12
    baud_rate: 9600

  pump_2:
    type_name: pump
    id: 14
    connection_type: serial
    identifier: 14
    baud_rate: 9600

  valve:
    type_name: valve
    id: 4
    connection_type: serial
    identifier: 4
    baud_rate: 9600

  balance:
    type_name: balance
    id: 9
    connection_type: serial
    identifier: 9
    baud_rate: 9600

  relay_1:
      type_name: relay
      id: 10
      connection_type: hid
      identifier: XFw/XEhJRCNWSURfMTZDMCZQSURfMDVERiM4JjIwZDg3NDJmJjAmMDAwMCN7NGQxZTU1YjItZjE2Zi0xMWNmLTg4Y2ItMDAxMTExMDAwMDMwfQ==

  relay_2:
    type_name: relay
    id: 11
    connection_type: hid
    identifier: XFw/XEhJRCNWSURfMTZDMCZQSURfMDVERiM4JmJlNDA3NDAmMCYwMDAwI3s0ZDFlNTViMi1mMTZmLTExY2YtODhjYi0wMDExMTEwMDAwMzB9